### ISSUE TITLE
Unsupported operation: Unable to load RTL-SDR library.

### ISSUE THREAD

**Issue by thoeve** [renggli/dart-rtlsdr#1]
For the last couple of hours I've been trying to get your library to work in my Flutter (Android) project. 

I imported that library as followed through the pubspec.yaml

    rtlsdr:
       git:
          url: git://github.com/renggli/dart-rtlsdr.git
          ref: main

Unfortunately when I run the following code.

    final device = RtlSdr();
    print(device.name);

The following error appears on build:

```
  Unsupported operation: Unable to load RTL-SDR library.
  The relevant error-causing widget was: 
    MyHomePage MyHomePage:file:///F:/Projects/siren/lib/main.dart:27:13
  When the exception was thrown, this was the stack: 
  #0      loadLibrary (package:rtlsdr/src/ffi/library.dart:53:3)
  #1      bindings (package:rtlsdr/src/ffi/bindings.dart:15:61)
  #2      RtlSdr._getName (package:rtlsdr/src/rtlsdr.dart:45:24)
  #3      RtlSdr.name (package:rtlsdr/src/rtlsdr.dart:43:22)
  #4      RtlSdr.name (package:rtlsdr/src/rtlsdr.dart)
  #5      _MyHomePageState._connect (package:siren/main.dart:67:18)
  #6      _MyHomePageState.build (package:siren/main.dart:96:5)
  #7      StatefulElement.build (package:flutter/src/widgets/framework.dart:4705:27)
```

Any clue what could cause this error? It seems it's because I'm missing the librtlsdr lib but I can't seem to figure out which or how I have to add it to the project.

**Comment by renggli** [comment]
The error happens when the library cannot be found. You need to install it on your system. For Android that is presumably a file called `librtlsdr.so`, for Windows `rtlsdr.dll`. 

However, I have never tried on either of these platforms. You might need to fix the code in [lib/src/ffi/library.dart](https://github.com/renggli/dart-rtlsdr/blob/main/lib/src/ffi/library.dart#L10). Happy to accept a pull request.

**Comment by thoeve** [comment]
I reckon you have no idea how to install the librtlsdr.so for Android? Because I can't to seem to be able to figure it out. There is something in the Flutter documentation but it doesn't help much. 

https://docs.flutter.dev/development/platform-integration/c-interop#platform-library-1

**Comment by renggli** [comment]
I have no experience with Flutter and FFI. I have built this package on Mac OS X, and I know that people have been successfully used the package on Linux. I recommend asking the Flutter community for help with FFI code. I don't think there is anything inherently stopping this package from working on Flutter, you just need to make it find and load the right native libraries.
