### ISSUE TITLE
The lower bound of "sdk: '>=2.7.0 <3.0.0'" must be 2.12.0 or higher to enable null safety.

### ISSUE THREAD

**Issue by nudyk** [renggli/dart-rtlsdr#2]
test> dart --version && flutter --version && flutter pub add rtlsdr
Dart SDK version: 3.1.2 (stable) (Tue Sep 12 16:26:23 2023 +0000) on "linux_x64"
Flutter 3.13.5 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 12fccda598 (7 days ago) • 2023-09-19 13:56:11 -0700
Engine • revision bd986c5ed2
Tools • Dart 3.1.2 • DevTools 2.25.0
Note: collection is pinned to version 1.17.2 by flutter from the flutter SDK.
See https://dart.dev/go/sdk-version-pinning for details.

The current Dart SDK version is 3.1.2.

Because every version of flutter from sdk depends on collection 1.17.2 and more >=4.0.1 depends on collection ^1.18.0, flutter from sdk
  is incompatible with more >=4.0.1.
And because rtlsdr >=0.0.6 depends on more ^4.0.1 and rtlsdr <0.0.6 doesn't support null safety, flutter from sdk is incompatible with
  rtlsdr.
So, because test depends on both flutter from sdk and rtlsdr any, version solving failed.

The lower bound of "sdk: '>=2.7.0 <3.0.0'" must be 2.12.0 or higher to enable null safety.
For details, see https://dart.dev/null-safety

**Comment by renggli** [comment]
From a practical standpoint I am unable to test with older package versions. New releases are always published with the latest stable dependencies. Consider using [dependency overrides](https://dart.dev/tools/pub/dependencies#dependency-overrides) or sticking with an older version of this package until your dependencies have caught up.

**Comment by nudyk** [comment]
But it run for:
Dart SDK version is 3.1.2 and Flutter 3.13.5. I try add rtlsdr 0.0.6.
dart pub add rtlsdr - working(in dart project, not in flutter project)
flutter pub add rtlsdr - not working and show this error
It new flutter project created by: flutter create test
